---
title: Portfolio — Denis Moulin
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
  experiences:
    title: experiences
    output: true
    permalink: "/xp/:title.html"
  notes:
    title: notes
    output: true
    permalink: "/n/:title.html"
  posts:
    title: posts
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/p/:year/:title.html"
    description:
    featured: false
    preview: false
    is_post: true
    banner: false
    cover:
    header:
    matters:
    period:
    external: false
    link:
banner:
author: Denis Moulin
firstname: Denis
email: moulin.denis@gmail.com
description: Portfolio of Designer Denis Moulin.
baseurl: ''
url: ''
twitter_username: _dmoulin
github_username: denismoulin
local: Montréal
markdown: kramdown
theme: minima
exclude:
- README
- Gemfile
- Gemfile.lock
- feed.xml
